version: '3'

volumes:
  postgresdata:

services:
  postgres:
    container_name: active_workflow_db
    restart: always
    image: docker.io/postgres:9.6-alpine
    env_file:
      - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  active_workflow_web:
    container_name: active_workflow_web
    restart: always
    #image: docker.io/automaticmode/active_workflow:0.9.17
    build:
      context: ./
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    env_file:
      - .env
    environment:
      RAILS_ENV: 'production'
    ports:
      - 3000:3000
    links:
      - postgres
    command: /scripts/init

  active_workflow_scheduler:
    container_name: active_workflow_scheduler
    restart: always
    #image: docker.io/automaticmode/active_workflow:0.9.17
    build:
      context: ./
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    env_file:
      - .env
    environment:
      RAILS_ENV: 'production'
    links:
      - postgres
    command: bundle exec rails runner bin/scheduler.rb

  active_workflow_worker:
    container_name: active_workflow_worker
    restart: always
    #image: docker.io/automaticmode/active_workflow:0.9.17
    build:
      context: ./
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    env_file:
      - .env
    environment:
      RAILS_ENV: 'production'
    links:
      - postgres
    command: bundle exec script/delayed_job -n 1 run
